### ISSUE TITLE
Recurring ticket date 

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#205] opened 2021-09-08 20:14 UTC
Change "today" to due date
![image](https://user-images.githubusercontent.com/71300724/132578237-0150ccb7-628b-40f4-a644-db006e5c7632.png)

**Comment by meomancer** [comment] 2021-09-10 03:41
Hi @tjaartvdb 
CC @timlinux @Andrevdb 

Should we change it to "From Start Date" instead "Due Date"
It will create confusion because we have Start Date on the ticket

**Comment by tjaartvdb** [comment] 2021-09-10 14:32
@meomancer  - Agreed,  change it to "From Start Date" instead "Due Date"

**Comment by meomancer** [comment] 2021-09-15 09:30
This is updated
Could you check it @tjaartvdb @Andrevdb ?

**Comment by tjaartvdb** [comment] 2021-09-16 01:41
@meomancer I get a "Server Error (500)" when submitting a ticket  - Please check

**Comment by meomancer** [comment] 2021-09-16 02:55
hi @tjaartvdb 
i can't reproduce the error

Could you provide what user did you use? What project and asset and what are the values for the new ticket?
Thank you

**Comment by meomancer** [comment] 2021-11-25 03:07
I'm going to close this ticket
create new ticket for new review

**Closed by meomancer** 2021-11-25 03:07 UTC
Labels: medium priority, september 2021 release
